### ISSUE TITLE
Installation started failing on Python 3.6 RHEL EC2 instance

### ISSUE THREAD

**Issue by pratibhagupta2109** [ross/requests-futures#86]
I am using requests-futures library since a long, but it has suddenly started failing to install during build deployment phase.
I am not sure if requests-futures is not fully supported on py3.6 or if there is something changed in my setup environment. 

I am getting following errors while installing requests-futures package:
Downloading https://files.pythonhosted.org/packages/47/c4/fd48d1ac5110a5457c71ac7cc4caa93da10a80b8de71112430e439bdee22/requests-futures-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lbe0dcsy/requests-futures/setup.py", line 51, in <module>
        'Programming Language :: Python :: 3.5',
      File "/usr/lib64/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.6/dist-packages/setuptools/dist.py", line 325, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python3.6/dist-packages/setuptools/dist.py", line 446, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 855, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/usr/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1127, in best_match
        return self.obtain(req, installer)
      File "/usr/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 1139, in obtain
        return installer(requirement)
      File "/usr/lib/python3.6/dist-packages/setuptools/dist.py", line 518, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/lib/python3.6/dist-packages/setuptools/command/easy_install.py", line 679, in easy_install
        not self.always_copy, self.local_index
      File "/usr/lib/python3.6/dist-packages/setuptools/package_index.py", line 636, in fetch_distribution
        dist = find(requirement)
      File "/usr/lib/python3.6/dist-packages/setuptools/package_index.py", line 617, in find
        dist.download_location = self.download(dist.location, tmpdir)
      File "/usr/lib/python3.6/dist-packages/setuptools/package_index.py", line 566, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "/usr/lib/python3.6/dist-packages/setuptools/package_index.py", line 805, in _download_url
        return self._attempt_download(url, filename)
      File "/usr/lib/python3.6/dist-packages/setuptools/package_index.py", line 811, in _attempt_download
        headers = self._download_to(url, filename)
      File "/usr/lib/python3.6/dist-packages/setuptools/package_index.py", line 734, in _download_to
        self.check_hash(checker, filename, tfp)
      File "/usr/lib/python3.6/dist-packages/setuptools/package_index.py", line 511, in check_hash
        checker.hash.name, os.path.basename(filename))
    distutils.errors.DistutilsError: sha256 validation failed for setuptools-41.2.0.zip; possible download problem?
Pip version pip 9.0.3

**Comment by ross** [comment]
This doesn't look to be related to request futures directly and is a problem with one of it's dependencies, setuptools, which is a general base dependency of most python projects. I'm not familiar enough with python versioning to know the details, but I believe 2.6 isn't a currently supported minor version/tree. It was EOLd (end of life) in 2013 - https://www.python.org/dev/peps/pep-0361/.
