### ISSUE TITLE
RuntimeError: dictionary changed size during iteration

### ISSUE THREAD

**Issue by eevleevs** [ross/requests-futures#93]
Hi, I am often getting the error below when calling a result. Any insight?

```Traceback (most recent call last):
File "services.py", line 60, in wrapper
return function(*args, **kwargs)
File "services.py", line 488, in start_period
future.result()
File "/usr/local/lib-python/3/concurrent/futures/_base.py", line 425, in result
return self.__get_result()
File "/usr/local/lib-python/3/concurrent/futures/_base.py", line 384, in __get_result
raise self._exception
File "/usr/local/lib-python/3/concurrent/futures/thread.py", line 56, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib_pypy/_functools.py", line 80, in __call__
return self._func(*(self._args + fargs), **fkeywords)
File "/usr/local/site-packages/requests/sessions.py", line 516, in request
prep = self.prepare_request(req)
File "/usr/local/site-packages/requests/sessions.py", line 459, in prepare_request
hooks=merge_hooks(request.hooks, self.hooks),
File "/usr/local/site-packages/requests/models.py", line 317, in prepare
self.prepare_body(data, files, json)
File "/usr/local/site-packages/requests/models.py", line 467, in prepare_body
body = complexjson.dumps(json)
File "/usr/local/lib-python/3/json/__init__.py", line 237, in dumps
return _default_encoder.encode(obj)
File "/usr/local/lib-python/3/json/encoder.py", line 190, in encode
self.__encode(o, markers, builder, 0)
File "/usr/local/lib-python/3/json/encoder.py", line 235, in __encode
self.__encode_dict(o, markers, builder, _current_indent_level)
File "/usr/local/lib-python/3/json/encoder.py", line 299, in __encode_dict
self.__encode(v, markers, builder, _current_indent_level)
File "/usr/local/lib-python/3/json/encoder.py", line 235, in __encode
self.__encode_dict(o, markers, builder, _current_indent_level)
File "/usr/local/lib-python/3/json/encoder.py", line 271, in __encode_dict
for key, v in items:
RuntimeError: dictionary changed size during iteration
```

**Comment by ross** [comment]
Without seeing the code it's hard to say, but it looks like maybe you're passing in a dict of parameters to send off to the request and then changing that dictionary elsewhere. This doesn't have anything to do with requests futures and is just a general "gotcha" with multi-threaded python. You can't change a dict while iterating over it:

```python
#!/usr/bin/env python

stuff = {
    'key': 'value',
    'foo': 'bar',
}

for k, v in stuff.items():
    stuff['another'] = 42
    print(f'{k}: {v}')
```

```
otter:tmp ross$ python3 fighting.py
key: value
Traceback (most recent call last):
  File "fighting.py", line 8, in <module>
    for k, v in stuff.items():
RuntimeError: dictionary changed size during iteration
otter:tmp ross$
```

My suggestion would be to make sure that the data you're sending in to the requests is a fresh dictionary each time. 

E.g. don't reuse a dict like (untested pseudo code):

```python
data = {
    'shared': 'value',
}
for i in range(100):
    data['i'] = i
    future = sess.get(url, data=data)
```

Either create it new each time or do a copy by wrapping it with `dict()`, which will only work if there are no nested keys, e.g.

```python
future = session.get(url, data=dict(data))
```

**Comment by eevleevs** [comment]
Thank, you are right. It was unclear to me what was happening, because the exception is raised by the result rather than the request.

If there are nested keys, one could make a copy with `copy.deepcopy()`.

**Comment by ross** [comment]
> Thanks, you are right. It was unclear to me what was happening, because the exception is raised by the result rather than the request.

That's how future objects work. When their background work involves an exception it's stored up until the result is fetched so that i can be handled at that point.
