### ISSUE TITLE
Setup issue in elasticbeanstalk 

### ISSUE THREAD

**Issue by samims** [ross/requests-futures#95]
I was trying to install this library on elasticbeanstalk where python version is 2.7 and requests version is 2.9.1 and futures version is 3.2.0 but I am getting the below error. Kindly can anyone tell why this is happening and how to resolve this?

```
  Collecting requests-futures>=1.0.0
    Downloading requests-futures-1.0.0.tar.gz (10 kB)
      ERROR: Command errored out with exit status 1:
       command: /opt/python/run/venv/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ESsE8X/requests-futures/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ESsE8X/requests-futures/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-h_E3Vo
           cwd: /tmp/pip-install-ESsE8X/requests-futures/
      Complete output (51 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-install-ESsE8X/requests-futures/setup.py", line 51, in <module>
          'Programming Language :: Python :: 3.5',
        File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
          _setup_distribution = dist = klass(attrs)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
          self.fetch_build_eggs(attrs['setup_requires'])
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
          replace_conflicting=True,
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 850, in resolve
          dist = best[req.key] = env.best_match(req, ws, installer)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1122, in best_match
          return self.obtain(req, installer)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1134, in obtain
          return installer(requirement)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
          return cmd.easy_install(req)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1101, in run_setup
          run_setup(setup_script, args)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in run_setup
          with setup_context(setup_dir):
        File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
          return self.gen.next()
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 198, in setup_context
          yield
        File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
          self.gen.throw(type, value, traceback)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 169, in save_modules
          saved_exc.resume()
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 144, in resume
          six.reraise(type, exc, self._tb)
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 157, in save_modules
          yield saved
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 197, in setup_context
          __import__('setuptools')
        File "setuptools/__init__.py", line 16, in <module>
        File "/opt/python/run/venv/local/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
          __import__(extant)
        File "pkg_resources/__init__.py", line 1380
          raise SyntaxError(e) from e
                                  ^
      SyntaxError: invalid syntax
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ross** [comment]
This doesn't look to be related to requests-futures itself and is more likely an issue with the details of the env, setuptools etc.

**Comment by ross** [comment]
Yeah. I'm actually getting this locally when i just try to update setuptools and pip in a 2.7 env at the same time which has been part of an alias I've used to create virtualenvs for a long time.

```
otter:tmp ross$ virtualenv env --python=`which python2` && source env/bin/activate && pip install -U pip setuptools
New python executable in env/bin/python
Installing setuptools, pip, wheel...done.
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl
Collecting setuptools
  Using cached https://files.pythonhosted.org/packages/d9/d5/8c0f83909f6054a587018dc10f3feff0d9e3315b1b5d519c790996cbd724/setuptools-49.4.0.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "setuptools/__init__.py", line 19, in <module>
        import setuptools.version
      File "setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "pkg_resources/__init__.py", line 1380
        raise SyntaxError(e) from e
                                ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/99/snfh5j_92wqfg1m2nhhb8z7r0000gn/T/pip-build-LhzZ7q/setuptools
You are using pip version 7.1.2, however version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

If i install pip and setuptools in separate rounds it seems to work:

```
otter:tmp ross$ deactivate; rm -rf env && virtualenv env --python=`which python2` && source env/bin/activate && pip install -U pip && pip install -U setuptools
-bash: deactivate: command not found
New python executable in env/bin/python
Installing setuptools, pip, wheel...done.
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5a/4a/39400ff9b36e719bdf8f31c99fe1fa7842a42fa77432e584f707a5080063/pip-20.2.2-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 7.1.2
    Uninstalling pip-7.1.2:
      Successfully uninstalled pip-7.1.2
Successfully installed pip-20.2.2
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting setuptools
  Using cached setuptools-44.1.1-py2.py3-none-any.whl (583 kB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 18.2
    Uninstalling setuptools-18.2:
      Successfully uninstalled setuptools-18.2
Successfully installed setuptools-44.1.1
```

My guess is that newer setuptools versions don't work with older pip versions. Maybe try updating `pip` with `pip install -U pip` before installing anything else.
